### ISSUE TITLE
Lack of a license

### ISSUE THREAD

**Issue by Archivist062** [manoharmukku/multilayer-perceptron-in-c#1]
Hello there.

I would like to ask if it were possible to add a license to this code. I was hoping to use it to make a small MLP library for [GNU Guile ](https://www.gnu.org/software/guile/) and if you are fine with that I would love you to add a license to the repo to guide me on what you are fine or not about this.

Thanks in advance

**Comment by manoharmukku** [comment]
Hello

I have added MIT License to the code. You are free to use the code for your purpose without any restrictions.

Thank you
